### ISSUE TITLE
Error: json.decoder.JSONDecodeError: Expecting value: line 1 colu

### ISSUE THREAD

**Issue by adrienjoly** [adrienjoly/backup-scripts#1]
```sh
$ ./backup.sh && ./diff-changes.sh && ./zip-and-upload.sh && ./clean-up.sh
Backing up trello boards to a subdirectory of /Users/adrienjoly/dev/adrienjoly/backup-scripts/trello ...
Unable to find image 'jtpio/trello-full-backup:latest' locally
latest: Pulling from jtpio/trello-full-backup
486a8e636d62: Pull complete 
6e3b49f9e4bd: Pull complete 
5ac287e38e18: Pull complete 
f45fc85a10cb: Pull complete 
fe4261a7371c: Pull complete 
f7188ea336f0: Pull complete 
207999969895: Pull complete 
Digest: sha256:102cef558fcc1ef5e72a5e68ab84e7a8d5bf0faa4f524e540a392d4fd9564fa0
Status: Downloaded newer image for jtpio/trello-full-backup:latest
==== Backup initiated
Backing up to: 2020-01-26_14-15-55_backup
Incremental: False
Tokenize: False
Backup closed board: False
Backup archived lists: False
Backup archived cards: False
Attachment size limit (bytes): -1
==== 

Traceback (most recent call last):
  File "/usr/local/bin/trello-full-backup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/trello_full_backup/__init__.py", line 5, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/trello_full_backup/backup.py", line 286, in cli
    org_boards_data['me'] = requests.get(my_boards_url).json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 886, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 colu
```

**Comment by adrienjoly** [comment]
Same error as https://github.com/jtpio/trello-full-backup/issues/27

**Comment by adrienjoly** [comment]
As mentioned in https://community.atlassian.com/t5/Trello-questions/Re-Re-Trello-API-Invalid-Key/qaq-p/1282962/comment-id/21077#M21077, I was getting this error because my Trello Token was wrong (32-chars-long instead of 64), because the Token generation URL I had provided in `.env.example` was missing the `response_type=token` parameter.
